language: objective-c
osx_image: xcode7.2
sudo: false
before_install:
- gem update fastlane
before_script:
- ./.fastlane/add-key.sh  
script:
- ./.fastlane/unittests.sh
after_success:
- ruby ./.fastlane/testflight.rb
notifications:
  slack: elpassion:rotzCblkkgDbH8aLQOklhtnA
env:
  global:
  - secure: gQILHGdQKHCSfPiBtclAnrxRoiDmYGVrHy45A+t4G4NarOAd2dkccIqF3Hgnq915CMCEJ8oilLoAibsNeUAkZdfQv5/CYdEIFzhHbKLfaPkr5kDH47EPCIDMu+MaLADcoXyxCA9ZGM3Rz5jOrwbi8DsRDNdz8guLUH1DYk6GotrwSlq23GeUW631Ft8P8u0T2PdMMdS31m1SYr6jgcAI0hlX9+EOz+koDgozeEI5y/2AArqU0HMeXmor+cqjAx5/xIVu26+4voSKtFS1+QHAN+HqUyCs+v4FAUp1UCddY6hsQj+hYs59ADy43s7bhdvlIbfD7aEvfaVbqJZzBqzNmkXbfT0qAtUzQivZbmWF9YeYGNnx9L1n18rY80hIi3jtH0COGj1AgoFhdyQtwQpzWZBSrUf0cUh/kVdh+fTGfnXIZj1bc2w6YS3r/i1uwc+eCTGL6Ks1HMP+TQzLHGIlMdzpzD7FZG9EPXEyhMp9ckQ6OPAX2xeTmLlVkplLlbNRVwMspjV7P2BAJblPJl+/OL1GNWQqNsQDP4ZgHnYEKk0vca8q+mV96K0yTqvnQ7bbBxYhFstJrjr/uOCdg0rJKk5Xl0dEPCttKjoMRXyy4xjA3c0G+Z4bLGekzS6pM7xcYUUIryTHFxBp0fJ+4ylJYlLAd/M+zyJvY7WwdBRQjNg=
  - secure: Z2RDE0VNdqj17jZaL648BLpyly2TH89NuuuBL4ZjYLT4Cas/wnFZ6DvNLac7qj4sHlbJBShbwMRU7no6r1OanyBYyRLPAxrh5r9ElomjxQI3fD1DHwdz/eHtMsXAx5ALBgKLq7aJkDKjwCftMUYTZ4ptpuz5LhwWxq8SgP+zHHBcxgiiPBO/LdM9R30Ua+5LEukhFfwqC0Q389wHxzU2JARUwFwd5acdsBG22VWXwirffor96MYVcujoIxYVlQP8wiUlh/WZXtMP9DNvVZCfTpeM6mzBvxk87bLn/T1V7Kem6vzqWlCDpBvBvX/VRijKAYsd2RmnYFDX+r6w5obT9bKDqyp6C/WLMCJMvS1Z3z57XjzhQg7wMD+iF3Iuc2OjK9gYRETX+LwSllx0HwzJin1t2BK9GJzPxFglJj89pWu3UPWjrOEhncpZK+aInkwYq0aAQEFetnBkVzQgmGKqT5I151FA1ai1NKzamR3piWGfmJYB6+tk29sd03HRD+/7183z5uw9IeQjaGnomGZ5yav+rXyOeF65djdwpdI1hxqzOsPDfKcOz0ajz6UF0/fW1WxHA84ncm7witIS7O5EbPmGb302tQ6biDbWP5lj0yJY0rmzbuA6AzxUZufvqBpSJSXtEC3AEfDtmM9m+1/vcEpOvf2h3NJg4xS5aM0cQGs=
